
workflow:
  rules:
    - if: >
        $CI_COMMIT_BRANCH == "main" &&
        $CI_PIPELINE_SOURCE != "schedule"

image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/lazy_images/selenium_ffmpeg

variables:
  UV_CACHE_DIR: $CI_PROJECT_DIR/.cache/uv

cache:
  key:
    files:
      - uv.lock
  paths:
    - .cache/uv
    - .venv

static_analysis:
  before_script:
    - uv sync --frozen
  script:
    - uv run pyright

self_test:
  needs:
    - static_analysis
  before_script:
    - uv sync --frozen
    # For saving videos
    - mkdir download
  script:
    - uv run python main.py --download-dir download --self-test

sonar_scan:
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  image:
    name: sonarsource/sonar-scanner-cli:12.1.0.3225_8.0.1
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"

push-github:
  needs:
    - static_analysis
    - self_test
    - sonar_scan
  image: $CI_REGISTRY/haward79/push2github/push2github:latest
  variables:
    GITHUB_URL: git@github.com:haward79/porn_video_downloader.git
  script:
    - push2github
