
workflow:
  rules:
    - if: >
        $CI_COMMIT_BRANCH == "main" &&
        $CI_PIPELINE_SOURCE != "schedule"

image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/lazy_images/selenium_ffmpeg

variables:
  UV_CACHE_DIR: $CI_PROJECT_DIR/.cache/uv

cache:
  key:
    files:
      - uv.lock
  paths:
    - .cache/uv
    - .venv

static_analysis:
  before_script:
    - uv sync --frozen
  script:
    - uv run pyright

self_test:
  needs:
    - static_analysis
  variables:
    SELENIUM_HEADLESS: false
    DISPLAY: ':99'
  before_script:
    - uv sync --frozen
    - mkdir download
  script:
    - Xvfb "$DISPLAY" -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - XVFB_PID="$!"
    - export BROWSER_VER_MAIN=$(chromium-browser --version | grep -Eo '\d+' | head -1 2> /dev/null)
    - uv run python main.py --download-dir download --self-test
    - cat CHECKME.log || true
    - kill "$XVFB_PID" || true

sonar_scan:
  needs:
    - static_analysis
    - self_test
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/lazy_images/sonar_scanner
  script:
    - entry.bash

push-github:
  needs:
    - static_analysis
    - self_test
    - sonar_scan
  image: $CI_REGISTRY/haward79/push2github/push2github:latest
  variables:
    GITHUB_URL: git@github.com:haward79/porn_video_downloader.git
  script:
    - push2github
